In [24]:
import pandas as pd

Data = {
    "Emp_ID": [
        101,102,103,104,105,106,107,108,109,110,
        111,112,113,114,115,116,117,118,119,120,
        121,122,123,124,125,126,127,128,129,130,
        131,132,133,134,135,136,137,138,139,140,
        141,142,143,144,145,146,147,148,149,150
    ],

    "NAME": [
        "Aman","Rahul","Joty","Nahe","Sohan","Ravi","Priya","Neha","Vikas","Pooja",
        "Arjun","Anjali","Rohit","Sneha","Karan","Simran","Deepak","Riya","Manish","Kavita",
        "Nikhil","Pallavi","Sumit","Shweta","Vivek","Komal","Aakash","Nisha","Raj","Meena",
        "Varun","Payal","Ashish","Tanya","Mohit","Sakshi","Ankit","Divya","Gaurav","Preeti",
        "Sachin","Rani","Abhishek","Muskan","Amit","Swati","Rakesh","Isha","Kunal","Sonam"
    ],

    "Department": [
        "IT","HR","IT","Sales","HR","Finance","IT","Marketing","Sales","HR",
        "IT","Finance","Sales","IT","HR","Marketing","IT","Finance","Sales","HR",
        "IT","Marketing","Finance","Sales","IT","HR","Finance","IT","Sales","Marketing",
        "HR","IT","Finance","Sales","Marketing","IT","HR","Finance","Sales","IT",
        "Marketing","HR","IT","Finance","Sales","HR","Marketing","IT","Finance","Sales"
    ],

    "Salary": [
        50000,40000,60000,45000,55000,52000,48000,65000,47000,43000,
        70000,58000,49000,62000,46000,54000,75000,51000,57000,44000,
        68000,53000,61000,47000,72000,42000,59000,64000,50000,56000,
        45000,73000,55000,48000,67000,52000,41000,63000,58000,76000,
        49000,46000,80000,54000,51000,60000,44000,69000,57000,62000
    ],

    "Age": [
        25,30,28,26,32,27,24,29,31,26,
        35,28,25,30,27,33,29,26,34,31,
        24,28,32,27,30,25,29,36,28,33,
        26,31,27,35,29,24,32,28,30,26,
        34,27,29,31,25,36,28,30,33,27
    ]
}

df = pd.DataFrame(Data)
df = pd.DataFrame(Data)

df

    Emp_ID      NAME Department  Salary  Age
0      101      Aman         IT   50000   25
1      102     Rahul         HR   40000   30
2      103      Joty         IT   60000   28
3      104      Nahe      Sales   45000   26
4      105     Sohan         HR   55000   32
5      106      Ravi    Finance   52000   27
6      107     Priya         IT   48000   24
7      108      Neha  Marketing   65000   29
8      109     Vikas      Sales   47000   31
9      110     Pooja         HR   43000   26
10     111     Arjun         IT   70000   35
11     112    Anjali    Finance   58000   28
12     113     Rohit      Sales   49000   25
13     114     Sneha         IT   62000   30
14     115     Karan         HR   46000   27
15     116    Simran  Marketing   54000   33
16     117    Deepak         IT   75000   29
17     118      Riya    Finance   51000   26
18     119    Manish      Sales   57000   34
19     120    Kavita         HR   44000   31
20     121    Nikhil         IT   68000   24
21     122   Pallavi  Marketing   53000   28
22     123     Sumit    Finance   61000   32
23     124    Shweta      Sales   47000   27
24     125     Vivek         IT   72000   30
25     126     Komal         HR   42000   25
26     127    Aakash    Finance   59000   29
27     128     Nisha         IT   64000   36
28     129       Raj      Sales   50000   28
29     130     Meena  Marketing   56000   33
30     131     Varun         HR   45000   26
31     132     Payal         IT   73000   31
32     133    Ashish    Finance   55000   27
33     134     Tanya      Sales   48000   35
34     135     Mohit  Marketing   67000   29
35     136    Sakshi         IT   52000   24
36     137     Ankit         HR   41000   32
37     138     Divya    Finance   63000   28
38     139    Gaurav      Sales   58000   30
39     140    Preeti         IT   76000   26
40     141    Sachin  Marketing   49000   34
41     142      Rani         HR   46000   27
42     143  Abhishek         IT   80000   29
43     144    Muskan    Finance   54000   31
44     145      Amit      Sales   51000   25
45     146     Swati         HR   60000   36
46     147    Rakesh  Marketing   44000   28
47     148      Isha         IT   69000   30
48     149     Kunal    Finance   57000   33
49     150     Sonam      Sales   62000   27

In [26]:
#loc
# select row and columns using tables(names)
print(df.loc[0])
print(df.loc[0,"Salary"])

Emp_ID          101
NAME           Aman
Department       IT
Salary        50000
Age              25
Name: 0, dtype: object
50000

In [27]:
# print the name and salary of the first row
print(df.loc[0,["NAME","Salary"]])

NAME       Aman
Salary    50000
Name: 0, dtype: object

In [28]:
#print the name and salary columns for all rows
print (df.loc[:,["NAME","Salary"]])

        NAME  Salary
0       Aman   50000
1      Rahul   40000
2       Joty   60000
3       Nahe   45000
4      Sohan   55000
5       Ravi   52000
6      Priya   48000
7       Neha   65000
8      Vikas   47000
9      Pooja   43000
10     Arjun   70000
11    Anjali   58000
12     Rohit   49000
13     Sneha   62000
14     Karan   46000
15    Simran   54000
16    Deepak   75000
17      Riya   51000
18    Manish   57000
19    Kavita   44000
20    Nikhil   68000
21   Pallavi   53000
22     Sumit   61000
23    Shweta   47000
24     Vivek   72000
25     Komal   42000
26    Aakash   59000
27     Nisha   64000
28       Raj   50000
29     Meena   56000
30     Varun   45000
31     Payal   73000
32    Ashish   55000
33     Tanya   48000
34     Mohit   67000
35    Sakshi   52000
36     Ankit   41000
37     Divya   63000
38    Gaurav   58000
39    Preeti   76000
40    Sachin   49000
41      Rani   46000
42  Abhishek   80000
43    Muskan   54000
44      Amit   51000
45     Swati   60000
46    Rakesh   44000
47      Isha   69000
48     Kunal   57000
49     Sonam   62000

In [30]:
# Highest salary
print(df[df["Salary"]==df["Salary"].max()])

    Emp_ID      NAME Department  Salary  Age
42     143  Abhishek         IT   80000   29

In [33]:

# Salary highest to lowest order
print(df.sort_values("Salary", ascending=False))

    Emp_ID      NAME Department  Salary  Age
42     143  Abhishek         IT   80000   29
39     140    Preeti         IT   76000   26
16     117    Deepak         IT   75000   29
31     132     Payal         IT   73000   31
24     125     Vivek         IT   72000   30
10     111     Arjun         IT   70000   35
47     148      Isha         IT   69000   30
20     121    Nikhil         IT   68000   24
34     135     Mohit  Marketing   67000   29
7      108      Neha  Marketing   65000   29
27     128     Nisha         IT   64000   36
37     138     Divya    Finance   63000   28
49     150     Sonam      Sales   62000   27
13     114     Sneha         IT   62000   30
22     123     Sumit    Finance   61000   32
45     146     Swati         HR   60000   36
2      103      Joty         IT   60000   28
26     127    Aakash    Finance   59000   29
11     112    Anjali    Finance   58000   28
38     139    Gaurav      Sales   58000   30
18     119    Manish      Sales   57000   34
48     149     Kunal    Finance   57000   33
29     130     Meena  Marketing   56000   33
32     133    Ashish    Finance   55000   27
4      105     Sohan         HR   55000   32
15     116    Simran  Marketing   54000   33
43     144    Muskan    Finance   54000   31
21     122   Pallavi  Marketing   53000   28
5      106      Ravi    Finance   52000   27
35     136    Sakshi         IT   52000   24
17     118      Riya    Finance   51000   26
44     145      Amit      Sales   51000   25
0      101      Aman         IT   50000   25
28     129       Raj      Sales   50000   28
12     113     Rohit      Sales   49000   25
40     141    Sachin  Marketing   49000   34
33     134     Tanya      Sales   48000   35
6      107     Priya         IT   48000   24
8      109     Vikas      Sales   47000   31
23     124    Shweta      Sales   47000   27
14     115     Karan         HR   46000   27
41     142      Rani         HR   46000   27
30     131     Varun         HR   45000   26
3      104      Nahe      Sales   45000   26
19     120    Kavita         HR   44000   31
46     147    Rakesh  Marketing   44000   28
9      110     Pooja         HR   43000   26
25     126     Komal         HR   42000   25
36     137     Ankit         HR   41000   32
1      102     Rahul         HR   40000   30

In [35]:
# salary short to highest
print(df.sort_values("Salary"))

    Emp_ID      NAME Department  Salary  Age
1      102     Rahul         HR   40000   30
36     137     Ankit         HR   41000   32
25     126     Komal         HR   42000   25
9      110     Pooja         HR   43000   26
46     147    Rakesh  Marketing   44000   28
19     120    Kavita         HR   44000   31
3      104      Nahe      Sales   45000   26
30     131     Varun         HR   45000   26
41     142      Rani         HR   46000   27
14     115     Karan         HR   46000   27
23     124    Shweta      Sales   47000   27
8      109     Vikas      Sales   47000   31
6      107     Priya         IT   48000   24
33     134     Tanya      Sales   48000   35
12     113     Rohit      Sales   49000   25
40     141    Sachin  Marketing   49000   34
28     129       Raj      Sales   50000   28
0      101      Aman         IT   50000   25
17     118      Riya    Finance   51000   26
44     145      Amit      Sales   51000   25
35     136    Sakshi         IT   52000   24
5      106      Ravi    Finance   52000   27
21     122   Pallavi  Marketing   53000   28
43     144    Muskan    Finance   54000   31
15     116    Simran  Marketing   54000   33
4      105     Sohan         HR   55000   32
32     133    Ashish    Finance   55000   27
29     130     Meena  Marketing   56000   33
48     149     Kunal    Finance   57000   33
18     119    Manish      Sales   57000   34
11     112    Anjali    Finance   58000   28
38     139    Gaurav      Sales   58000   30
26     127    Aakash    Finance   59000   29
2      103      Joty         IT   60000   28
45     146     Swati         HR   60000   36
22     123     Sumit    Finance   61000   32
49     150     Sonam      Sales   62000   27
13     114     Sneha         IT   62000   30
37     138     Divya    Finance   63000   28
27     128     Nisha         IT   64000   36
7      108      Neha  Marketing   65000   29
34     135     Mohit  Marketing   67000   29
20     121    Nikhil         IT   68000   24
47     148      Isha         IT   69000   30
10     111     Arjun         IT   70000   35
24     125     Vivek         IT   72000   30
31     132     Payal         IT   73000   31
16     117    Deepak         IT   75000   29
39     140    Preeti         IT   76000   26
42     143  Abhishek         IT   80000   29

In [36]:
# you want only the first persons name
print(df.loc[0,"NAME"])

Aman

In [38]:
#secont highest salary
print(df.sort_values("Salary", ascending=False).iloc[1])

Emp_ID           140
NAME          Preeti
Department        IT
Salary         76000
Age               26
Name: 39, dtype: object

In [40]:
#Top 3 salary only
print(df["Salary"].nlargest(3))

42    80000
39    76000
16    75000
Name: Salary, dtype: int64

In [41]:
# Top 3 highest salary
print(df["Salary"].nlargest(3).iloc[-1])

75000

In [44]:
# Top 3 employees with their details
print(df.nlargest(6,"Salary"))

    Emp_ID      NAME Department  Salary  Age
42     143  Abhishek         IT   80000   29
39     140    Preeti         IT   76000   26
16     117    Deepak         IT   75000   29
31     132     Payal         IT   73000   31
24     125     Vivek         IT   72000   30
10     111     Arjun         IT   70000   35

In [46]:
# loc
# selects rows and columns using index positions
print(df.iloc[:, 1:3])

        NAME Department
0       Aman         IT
1      Rahul         HR
2       Joty         IT
3       Nahe      Sales
4      Sohan         HR
5       Ravi    Finance
6      Priya         IT
7       Neha  Marketing
8      Vikas      Sales
9      Pooja         HR
10     Arjun         IT
11    Anjali    Finance
12     Rohit      Sales
13     Sneha         IT
14     Karan         HR
15    Simran  Marketing
16    Deepak         IT
17      Riya    Finance
18    Manish      Sales
19    Kavita         HR
20    Nikhil         IT
21   Pallavi  Marketing
22     Sumit    Finance
23    Shweta      Sales
24     Vivek         IT
25     Komal         HR
26    Aakash    Finance
27     Nisha         IT
28       Raj      Sales
29     Meena  Marketing
30     Varun         HR
31     Payal         IT
32    Ashish    Finance
33     Tanya      Sales
34     Mohit  Marketing
35    Sakshi         IT
36     Ankit         HR
37     Divya    Finance
38    Gaurav      Sales
39    Preeti         IT
40    Sachin  Marketing
41      Rani         HR
42  Abhishek         IT
43    Muskan    Finance
44      Amit      Sales
45     Swati         HR
46    Rakesh  Marketing
47      Isha         IT
48     Kunal    Finance
49     Sonam      Sales

In [49]:
# Data cleaning 
#Check the data
print(df.head())

   Emp_ID   NAME Department  Salary  Age
0     101   Aman         IT   50000   25
1     102  Rahul         HR   40000   30
2     103   Joty         IT   60000   28
3     104   Nahe      Sales   45000   26
4     105  Sohan         HR   55000   32

In [50]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      50 non-null     int64
 1   NAME        50 non-null     str
 2   Department  50 non-null     str
 3   Salary      50 non-null     int64
 4   Age         50 non-null     int64
dtypes: int64(3), str(2)
memory usage: 1.6 KB
None

In [51]:
print(df.shape)

(50, 5)

In [52]:
#Check duplicate rows
print(df.duplicated().sum())

0

In [54]:
#. Check missing values
print(df.isnull().sum())

Emp_ID        0
NAME          0
Department    0
Salary        0
Age           0
dtype: int64

In [59]:
print(df.dtypes)

Emp_ID        int64
NAME            str
Department      str
Salary        int64
Age           int64
dtype: object

In [62]:
#Check invalid values
print(df[df["Age"] < 18])
print(df[df["Salary"] < 0])

Empty DataFrame
Columns: [Emp_ID, NAME, Department, Salary, Age]
Index: []
Empty DataFrame
Columns: [Emp_ID, NAME, Department, Salary, Age]
Index: []

In [63]:
#Check invalid values
print(df[df["Age"] < 18])
print(df[df["Salary"] < 0])

Empty DataFrame
Columns: [Emp_ID, NAME, Department, Salary, Age]
Index: []
Empty DataFrame
Columns: [Emp_ID, NAME, Department, Salary, Age]
Index: []

In [64]:
#Check the cleaned data
print(df.head())
print(df.isnull().sum())
print(df.duplicated().sum())

   Emp_ID   NAME Department  Salary  Age
0     101   Aman         It   50000   25
1     102  Rahul         Hr   40000   30
2     103   Joty         It   60000   28
3     104   Nahe      Sales   45000   26
4     105  Sohan         Hr   55000   32
Emp_ID        0
NAME          0
Department    0
Salary        0
Age           0
dtype: int64
0

In [66]:
df.isnull()

    Emp_ID   NAME  Department  Salary    Age
0    False  False       False   False  False
1    False  False       False   False  False
2    False  False       False   False  False
3    False  False       False   False  False
4    False  False       False   False  False
5    False  False       False   False  False
6    False  False       False   False  False
7    False  False       False   False  False
8    False  False       False   False  False
9    False  False       False   False  False
10   False  False       False   False  False
11   False  False       False   False  False
12   False  False       False   False  False
13   False  False       False   False  False
14   False  False       False   False  False
15   False  False       False   False  False
16   False  False       False   False  False
17   False  False       False   False  False
18   False  False       False   False  False
19   False  False       False   False  False
20   False  False       False   False  False
21   False  False       False   False  False
22   False  False       False   False  False
23   False  False       False   False  False
24   False  False       False   False  False
25   False  False       False   False  False
26   False  False       False   False  False
27   False  False       False   False  False
28   False  False       False   False  False
29   False  False       False   False  False
30   False  False       False   False  False
31   False  False       False   False  False
32   False  False       False   False  False
33   False  False       False   False  False
34   False  False       False   False  False
35   False  False       False   False  False
36   False  False       False   False  False
37   False  False       False   False  False
38   False  False       False   False  False
39   False  False       False   False  False
40   False  False       False   False  False
41   False  False       False   False  False
42   False  False       False   False  False
43   False  False       False   False  False
44   False  False       False   False  False
45   False  False       False   False  False
46   False  False       False   False  False
47   False  False       False   False  False
48   False  False       False   False  False
49   False  False       False   False  False

In [73]:
#Sorting
df.sort_values("Salary")

    Emp_ID      NAME Department  Salary  Age
1      102     Rahul         Hr   40000   30
36     137     Ankit         Hr   41000   32
25     126     Komal         Hr   42000   25
9      110     Pooja         Hr   43000   26
46     147    Rakesh  Marketing   44000   28
19     120    Kavita         Hr   44000   31
3      104      Nahe      Sales   45000   26
30     131     Varun         Hr   45000   26
41     142      Rani         Hr   46000   27
14     115     Karan         Hr   46000   27
23     124    Shweta      Sales   47000   27
8      109     Vikas      Sales   47000   31
6      107     Priya         It   48000   24
33     134     Tanya      Sales   48000   35
12     113     Rohit      Sales   49000   25
40     141    Sachin  Marketing   49000   34
28     129       Raj      Sales   50000   28
0      101      Aman         It   50000   25
17     118      Riya    Finance   51000   26
44     145      Amit      Sales   51000   25
35     136    Sakshi         It   52000   24
5      106      Ravi    Finance   52000   27
21     122   Pallavi  Marketing   53000   28
43     144    Muskan    Finance   54000   31
15     116    Simran  Marketing   54000   33
4      105     Sohan         Hr   55000   32
32     133    Ashish    Finance   55000   27
29     130     Meena  Marketing   56000   33
48     149     Kunal    Finance   57000   33
18     119    Manish      Sales   57000   34
11     112    Anjali    Finance   58000   28
38     139    Gaurav      Sales   58000   30
26     127    Aakash    Finance   59000   29
2      103      Joty         It   60000   28
45     146     Swati         Hr   60000   36
22     123     Sumit    Finance   61000   32
49     150     Sonam      Sales   62000   27
13     114     Sneha         It   62000   30
37     138     Divya    Finance   63000   28
27     128     Nisha         It   64000   36
7      108      Neha  Marketing   65000   29
34     135     Mohit  Marketing   67000   29
20     121    Nikhil         It   68000   24
47     148      Isha         It   69000   30
10     111     Arjun         It   70000   35
24     125     Vivek         It   72000   30
31     132     Payal         It   73000   31
16     117    Deepak         It   75000   29
39     140    Preeti         It   76000   26
42     143  Abhishek         It   80000   29

In [74]:
df.sort_values("Salary", ascending=False)

    Emp_ID      NAME Department  Salary  Age
42     143  Abhishek         It   80000   29
39     140    Preeti         It   76000   26
16     117    Deepak         It   75000   29
31     132     Payal         It   73000   31
24     125     Vivek         It   72000   30
10     111     Arjun         It   70000   35
47     148      Isha         It   69000   30
20     121    Nikhil         It   68000   24
34     135     Mohit  Marketing   67000   29
7      108      Neha  Marketing   65000   29
27     128     Nisha         It   64000   36
37     138     Divya    Finance   63000   28
49     150     Sonam      Sales   62000   27
13     114     Sneha         It   62000   30
22     123     Sumit    Finance   61000   32
45     146     Swati         Hr   60000   36
2      103      Joty         It   60000   28
26     127    Aakash    Finance   59000   29
11     112    Anjali    Finance   58000   28
38     139    Gaurav      Sales   58000   30
18     119    Manish      Sales   57000   34
48     149     Kunal    Finance   57000   33
29     130     Meena  Marketing   56000   33
32     133    Ashish    Finance   55000   27
4      105     Sohan         Hr   55000   32
15     116    Simran  Marketing   54000   33
43     144    Muskan    Finance   54000   31
21     122   Pallavi  Marketing   53000   28
5      106      Ravi    Finance   52000   27
35     136    Sakshi         It   52000   24
17     118      Riya    Finance   51000   26
44     145      Amit      Sales   51000   25
0      101      Aman         It   50000   25
28     129       Raj      Sales   50000   28
12     113     Rohit      Sales   49000   25
40     141    Sachin  Marketing   49000   34
33     134     Tanya      Sales   48000   35
6      107     Priya         It   48000   24
8      109     Vikas      Sales   47000   31
23     124    Shweta      Sales   47000   27
14     115     Karan         Hr   46000   27
41     142      Rani         Hr   46000   27
30     131     Varun         Hr   45000   26
3      104      Nahe      Sales   45000   26
19     120    Kavita         Hr   44000   31
46     147    Rakesh  Marketing   44000   28
9      110     Pooja         Hr   43000   26
25     126     Komal         Hr   42000   25
36     137     Ankit         Hr   41000   32
1      102     Rahul         Hr   40000   30